config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('',include('homepage.urls',namespace="homepage")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from unicodedata import name
from django.urls import path
from djgeojson.views import GeoJSONLayerView
from .models import Building,Room
from .views import (
    CallGlovoAPiview,
    FilterWithCurrentLocation,
    index,
    map_search_view,
    GetBUildingAPIVIEW,
    GetRoom,
    map_detailed_page,
    FilterRoom,
    room_detailed_page,
    request_booking,
    listing_listview,
    book_request,
    saved_room,
    FilterSavedRoom,
    all_saved_rooms,
    unsaved_room,
    book_room_payment,
    payment_waiting,
    paid_rooms,
    payment_Processing,
    room_detailed_page_paid,
    SendHTML,
    SendContactMail,
    GetRoomAl,
    map_search_view_authenticated,
    PostLocationCoordinates,
    SendContactAdminMail,
    GetCoordinatesAndBounds
)

app_name = "homepage"
urlpatterns = [
    path('', index,name="homepage"),
    path('map_search',map_search_view,name="map_search"),
    path("all_buildinunsaved_roomgs/",GeoJSONLayerView.as_view(model=Building,properties=('agent','building_name','no_of_floors','no_of_Room','location_name','parking_space','security','tv_connection','account_number','owner','payment_deadline','penalties','approved','created')),name="all_buildings"),
    path('get_all_data/',GetBUildingAPIVIEW.as_view(),name="get_all_data"),
    path('room_name/',GetRoom.as_view(),name="get_room"),
    path('map_detailed/<id>/',map_detailed_page,name="map_detailed"),
    path('filter_room/',FilterRoom.as_view(),name="filtered_data"),
    path('room_detailed/<id>/',room_detailed_page,name="room_detailed"),
    path('room_detailed_paid/<id>/',room_detailed_page_paid,name="room_detailed_page_paid"),

    path('booking_request/<room_id>/<agent_id>/<user_id>/',request_booking,name="request_booking"),
    path('listing_listview/',listing_listview,name="listing_listview"),
    path('book_request/<id>/',book_request,name="book_request"),
    path('saved_rentals/<id>/',saved_room,name="saved_rentals"),
    path('filter_saved_rooms/',FilterSavedRoom.as_view(),name="filter_saved_rooms"),
    path('all_saved_rooms/',all_saved_rooms,name="all_saved_rooms"),
    path('unsaved_room/<id>/',unsaved_room,name="unsaved_rentals"),
    path('booking_payment/<id>/',book_room_payment,name="book_room_payment"),
    path("payment_waiting/",payment_waiting,name="payment_waiting"),
    path("paid_rooms/",paid_rooms,name="paid_rooms"),
    path("payment_Processing/",payment_Processing,name="payment_Processing"),
    path("send_mail/kanzi/",SendHTML.as_view()),
    path("send_email_contact_kanzi/",SendContactMail.as_view()),
    path("get_all_rooms/",GetRoomAl.as_view(),name="all_rm"),
    path("map_search_view_authenticated/",map_search_view_authenticated,name="map_search_view_authenticated"),
    path("post_location_coordinates/",PostLocationCoordinates.as_view()),
    path("send_em/",SendContactAdminMail.as_view()),
    path('call_glovo/',CallGlovoAPiview.as_view(),name="call_glovo"),
    path("search_with_lat/",FilterWithCurrentLocation.as_view(),name="search_with_lat_and_lon"),
    path("get_coordinates_and_bounds/",GetCoordinatesAndBounds.as_view(),name="get_coordinates_and_bounds")

  
]

payment/urls.py
from os import name
from django.urls import path

from .views import (


    LipaNaMpesa,
    confirmation_url,
    customer_to_business,
    LipaNaMpesaC2B

)

app_name = "payment"
urlpatterns = [
    path('lipa_na_mpesa/',LipaNaMpesa.as_view(),name="lipa_online_mpesa"),
    path("confirmation_url/",confirmation_url,name="sending_to_mpesa"),
    path("customer_to_business/",customer_to_business,name="customer_to_business"),
    path("pay_c2b/",LipaNaMpesaC2B.as_view(),name="c2b_p")
   
  
 

]

payment/models.py
from django.db import models
from rest_framework import serializers
from account.models import User
# from mainapp.models import Booking
from homepage.models import Room

# Create your models here.
class MpesaResquest(models.Model):
    user_id =  models.ForeignKey(User,on_delete=models.CASCADE)
    room_id =  models.ForeignKey(Room,on_delete=models.CASCADE)
    merchantRequestid =  models.CharField(max_length=255)
    chechoutrequestid =  models.CharField(max_length=255)
    responsecode =  models.CharField(max_length=10)
    responsedescription =  models.TextField()
    customerMessage =  models.TextField()
    status =  models.CharField(max_length=255,blank=True,null=True)
    request_id = models.CharField(max_length=255,blank=True,null=True)
    callback_url =  models.URLField(null=True,blank=True)

    def __str__(self):
        return self.merchantRequestid
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class MpesaQuery(BaseModel):
    mpesa_request_id =  models.ForeignKey(MpesaResquest,on_delete=models.CASCADE)
    response_code =  models.CharField(max_length=255)
    response_description =  models.TextField()
    merchant_id =  models.CharField(max_length=255)
    checkout_request_id =  models.CharField(max_length=255)
    result_code = models.CharField(max_length=255)
    result_description =  models.TextField()
    status = models.CharField(max_length=255)
    request_id =  models.TextField()


    def __str__(self):
        return self.response_code



class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=30, decimal_places=2)
    result_description = models.TextField()
    merchant_id = models.CharField(max_length=150,blank=True,null=True)
    checkout_request_id = models.CharField(max_length=150,blank=True,null=True)
    mpesaReceiptNumber = models.CharField(max_length=150,blank=True,null=True)
    name = models.CharField(max_length=150,blank=True,null=True)
    transaction_date = models.DateTimeField(blank=True,null=True)
    phone_number = models.CharField(max_length=150,blank=True,null=True)

    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'

    def __str__(self):
        return self.merchant_id

payment/forms.py
from django import forms
from django.core.exceptions import ValidationError

class CashAtHand(forms.Form):
    cash_at_hand = forms.IntegerField(widget=forms.NumberInput(
        attrs={  "type": "number", "style" : " color:#000000;width:100%;font-size:16px;border: 2px solid red;padding:10px"  , "placeholder" : "Cash At Hand" , "id" : "form_control_lgn_input" 
        
        }
    ))

    def clean(self,value):
        # data from the form is fetched using super function
        data = self.cleaned_data['cash_at_hand']
        if float(data)<= float(value):
            raise ValidationError("Enter Amount greater than delivery Amount")
        return data
        

    

payment/views.py
import io
import json
import os
from pprint import pp
import time
from datetime import datetime
from django.http import HttpResponse, JsonResponse,HttpResponseRedirect
from io import BytesIO

import stripe
from account.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.files.base import ContentFile, File
from django.core.mail import EmailMessage
from django.http import FileResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from homepage.models import BookingRequest, Room
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from payment.common.MpesaPaymentThread import PayViaMpesaThred
from payment.common.MpesaPaymentC2BThread import PayViaMpesaThredC2B
from payment.models import MpesaQuery, MpesaResquest

from .models import MpesaPayment
from .utils import validate_not_mobile

#Email imports

#####################
# Create your views here.



#mpesa callback




stripe.api_key = "sk_test_51HI1b9FXATpECfwyUyt6wwmfnXQpVKAEH2rruhHsnLkLGAdtmJCBRaztSq7JNmTJCzRCdxYXYrNwHWOSogJCB5tj00gNdKZDgd"

class LipaNaMpesa(APIView):
    def post(self,request):

        payment =  request.data['payment']
        data =json.loads(payment)
        print(data)
        user = User.objects.get(id = int(request.data['user_id']))
        room =  Room.objects.get(id = int(data['room_number']) )
        obj =  BookingRequest.objects.create(
            user = user,
            room = room,
            name = data['full_name'],
            email = data['emai_address'],
            contact_phone = data['contact_number']

        )
        current_site = get_current_site(request)

        # site_url = f"https://{current_site}/payments/confirmation_url/"
        site_url = "https://shrouded-reef-57090.herokuapp.com/payment/c2b/confirmation/"
        print(site_url)

        PayViaMpesaThred(data['mpesa_payment'],obj.id,1,room.id,user.id,data['emai_address'],site_url).start()

        return Response({"success":"ok"},status=status.HTTP_200_OK)


class PayWithStripe(APIView):
    def post(self,request):
        return Response({"success":"ok"})

@csrf_exempt 
def confirmation_url(request):
    if request.method == "POST":
      
        print(".................confirmation beginning...................")
        mpesa_body =request.body.decode('utf-8')
        mpesa_payment = json.loads(mpesa_body)
        body = mpesa_payment['Body']["stkCallback"]
        if body["ResultCode"] == 0:
            merchant_id = body['MerchantRequestID']
            checkout_request_id = body["CheckoutRequestID"]
            result_description = body['ResultDesc']
            callback_metadata = body['CallbackMetadata']['Item']
            amount = callback_metadata[0]['Value']
            MpesaReceiptNumber = callback_metadata[1]['Value']
            name = callback_metadata[2]['Name']
            transaction_date_year = str(callback_metadata[3]['Value'])[0:4]
            transaction_date_month = str(callback_metadata[3]['Value'])[4:6]
            transaction_date_day = str(callback_metadata[3]['Value'])[6:8]
            transaction_hours = str(callback_metadata[3]['Value'])[8:10]
            transaction_min = str(callback_metadata[3]['Value'])[10:12]
            transaction_sec = str(callback_metadata[3]['Value'])[12:14]
            day_string = transaction_date_year + "/" + transaction_date_month+ "/" + transaction_date_day + "  " + transaction_hours + ":" + transaction_min + ":" + transaction_sec + ".0"
            datetime_object = datetime.strptime(day_string, '%Y/%m/%d %H:%M:%S.%f')
            phone_number = callback_metadata[4]['Value']
            print("........saving details.................")
            payment,created = MpesaPayment.objects.get_or_create(merchant_id = merchant_id, checkout_request_id = checkout_request_id )
            payment.amount =  amount
            payment.result_description = result_description
            payment.merchant_id = merchant_id
            payment.checkout_request_id = checkout_request_id
            payment.mpesaReceiptNumber  = MpesaReceiptNumber
            payment.name = name
            payment.transaction_date  = datetime_object
            payment.phone_number  = phone_number
            payment.save()


            # payment = MpesaPayment(
            #     amount = amount,
            #     result_description= result_description,
            #     merchant_id= merchant_id,
            #     checkout_request_id=checkout_request_id,
            #     mpesaReceiptNumber= MpesaReceiptNumber,
            #     name= name,
            #     transaction_date=datetime_object,
            #     phone_number=phone_number

            # )
            # payment.save()
            print("...........saved details...................")
        print("........... redirecting ...................")
        return render(render,'sending_success_payment.html')

    context = {
        "ResultCode": 0,
        "ResultDesc": "Accepted"
    }

    return render(request,'sending_success_payment.html')


@login_required(login_url="account:sign_in")
def customer_to_business(request):
    return render(request,'awaiting_c2b.html')


class LipaNaMpesaC2B(APIView):
    def post(self,request):

        payment =  request.data

        data =json.loads(json.dumps(payment))
        print(data['payment'])
        ppy = json.loads(data['payment'])
        user = User.objects.get(id = int(request.data['user_id']))
        room =  Room.objects.get(id = int(1) )
        obj =  BookingRequest.objects.create(
            user = user,
            room = room,
            name = ppy['full_name'],
            email = ppy['email'],
            contact_phone = ppy['phone_number']

        )
        current_site = get_current_site(request)
        site_url = "https://shrouded-reef-57090.herokuapp.com/payment/c2b/confirmation/"
        PayViaMpesaThredC2B(ppy['phone_number'],obj.id,1,1,user.id,ppy['email'],site_url).start()

        

        return Response({"success":"ok"},status=status.HTTP_200_OK)

payment/templates/cash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">		
		<title>Twala Fish </title>
		
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'images\bg_sin.png' %}">
		
		<!-- Stylesheets -->
		<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
		<link href='vendor\unicons-2.0.1\css\unicons.css' rel='stylesheet'>
		<link href="{% static 'css\style.css' %}" rel="stylesheet">
		<link href="{% static 'css\responsive.css' %}" rel="stylesheet">
		<link href="{% static 'css\night-mode.css' %}" rel="stylesheet">
		<link href="{% static 'css\step-wizard.css' %}" rel="stylesheet">
		
		<!-- Vendor Stylesheets -->
		<link href="{% static 'vendor\fontawesome-free\css\all.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\bootstrap\css\bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'vendor\semantic\semantic.min.css' %}">	
		
	</head>

<body>
	<!-- Header Start -->
	<header class="header clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="top-header-group">
						<div class="top-header">
							<div class="res_main_logo">
								<a href="/"><img src="{% static 'images\bg.jpeg' %}" alt=""></a>
							</div>
							<div class="main_logo" id="logo">
                
								<a href="/"><img src="{% static 'images\P_ight.jpg' %}" alt=""></a>
								<a href="/"><img class="logo-inverse" src="{% static 'images\P_dark.jpg' %}" alt=""></a>
						   
							</div>
							<div class="header_right">
								<a href="#" class="report-btn hover-btn">Thank You</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->
	<!-- Body Start -->
	
		
	<div class="bill-dt-bg">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="bill-detail">
						<div class="bill-dt-step">
							<!-- messages -->
							{% if messages %}
							{% for message in messages %}
							<div class="alert alert-danger" role="alert">
								{{ message }}
							  </div>
							  {% endfor %}
							{% endif %}
							<!-- end messages -->
							<div class="bill-title">
								<h4>Items</h4>
							
							</div>
							<div class="bill-descp">
                                <div class="itm-ttl">{{cart_items}} items</div>
                                {% if cart.products %}
                                {% for p in cart.products.all %}
                                <span class="item-prdct">{{p.product_title }} 1kg</span>
                                {% endfor %}
                                {% endif %}
							
							</div>
                        </div>
                        <div class="bill-dt-step">
							<div class="bill-title">
								<h4>Delivery Address</h4>
							</div>
							<div class="bill-descp">
								<div class="itm-ttl"></div>
								<p class="bill-address">{{object.delivery_address.name}},{{object.delivery_address.phone}},{{object.delivery_address.email}}</p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Order Details</h4>
							</div>
							<div class="bill-descp">
								
								<p class="bill-dt-sl">Order ID - <span class="descp-bll-dt">{{object.order_id}}</span></p>
								<p class="bill-dt-sl">Items - <span class="descp-bll-dt">{{cart_items}}</span></p>
								<p class="bill-dt-sl">Timing - <span class="descp-bll-dt">{{delivery_time.date}}</span></p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment</h4>
							</div>
							<div class="bill-descp">
								<div class="total-checkout-group p-0 border-top-0">
									<div class="cart-total-dil">
										<h4>Subtotal</h4>
										<span>Ksh : {{object.cart.total }}</span>
									</div>
									<div class="cart-total-dil pt-3">
										<h4>Delivery Charges</h4>
										<span>Ksh : {{object.shipping_total }}</span>
									</div>
								</div>
								<div class="main-total-cart pl-0 pr-0 pb-0 border-bottom-0">
									<h2>Total</h2>
									<span>Ksh : {{object.total }}</span>
								</div>
							</div>
						</div>
						
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment Option</h4>
							</div>
							<div class="bill-descp">
								<p class="bill-dt-sl"><span class="dlr-ttl25 mr-1"><i class="uil uil-check-circle"></i></span>Cash on Delivery</p>
							</div>
						</div>
						<form method="POST">
							{% csrf_token %}

						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Enter Cash At Hand*</h4>
							</div>
							<div class="bill-descp">
								
									<input  type = "number" style = " color:#000000;width:100%;font-size:16px;border: 2px solid red;padding:10px"   placeholder = "Cash At Hand" , name = "cash_at_hand" >
							
							</div>
						</div>
						<div class="bill-dt-step">
							
							{% comment %} <div class="bill-title">
								<h4>Enter Cash At Hand*</h4>
							</div>
							<div class="bill-descp">
								{{cash_at_hand.cash_at_hand}}
							</div> {% endcomment %}
							

							<div class="bill-bottom">
								<div class="thnk-ordr">Continue with Order</div>
								
								
								
								
								<button class="print-btn hover-btn" type="submit" >{{delivery_method}}</button>
							</form>
							</div>
					
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Body End -->
	
	<!-- Javascripts -->
	<script src="{ static 'js\jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor\bootstrap\js\bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor\OwlCarousel\owl.carousel.js' %}"></script>
	<script src="{% static 'vendor\semantic\semantic.min.js' %}"></script>
	<script src="{% static 'js\jquery.countdown.min.js' %}"></script>
	<script src="{% static 'js\custom.js' %}"></script>
	<script src="{% static 'js\product.thumbnail.slider.js' %}"></script>
	<script src="{% static 'js\offset_overlay.js' %}"></script>
	<script src="{% static 'js\night-mode.js' %}"></script>
	<script>
		document.getElementById("form_control_lgn_input")
	</script>
	
	
</body>
</html>

payment/templates/mpesa.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">		
		<title>Twala Fish </title>
		
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'images\bg_sin.png' %}">
		
		<!-- Stylesheets -->
		<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
		<link href='vendor\unicons-2.0.1\css\unicons.css' rel='stylesheet'>
		<link href="{% static 'css\style.css' %}" rel="stylesheet">
		<link href="{% static 'css\responsive.css' %}" rel="stylesheet">
		<link href="{% static 'css\night-mode.css' %}" rel="stylesheet">
		<link href="{% static 'css\step-wizard.css' %}" rel="stylesheet">
		
		<!-- Vendor Stylesheets -->
		<link href="{% static 'vendor\fontawesome-free\css\all.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\bootstrap\css\bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'vendor\semantic\semantic.min.css' %}">	
		
	</head>

<body>
	<!-- Header Start -->
	<header class="header clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="top-header-group">
						<div class="top-header">
							<div class="res_main_logo">
								<a href="/"><img src="{% static 'images\bg.jpeg' %}" alt=""></a>
							</div>
							<div class="main_logo" id="logo">
                
								<a href="/"><img src="{% static 'images\P_ight.jpg' %}" alt=""></a>
								<a href="/"><img class="logo-inverse" src="{% static 'images\P_dark.jpg' %}" alt=""></a>
						   
							</div>
							<div class="header_right">
								<a href="#" class="report-btn hover-btn">Thank You</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->
	<!-- Body Start -->
	<div class="bill-dt-bg">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="bill-detail">
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Items</h4>
							</div>
							<div class="bill-descp">
                                <div class="itm-ttl">{{cart_items}} items</div>
                                {% if cart.products %}
                                {% for p in cart.products.all %}
                                <span class="item-prdct">{{p.product_title }} 1kg</span>
                                {% endfor %}
                                {% endif %}
							
							</div>
                        </div>
                        <div class="bill-dt-step">
							<div class="bill-title">
								<h4>Delivery Address</h4>
							</div>
							<div class="bill-descp">
								<div class="itm-ttl"></div>
								<p class="bill-address">{{object.delivery_address.name}},{{object.delivery_address.phone}},{{object.delivery_address.billing_profile}}</p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Order Details</h4>
							</div>
							<div class="bill-descp">
								
								<p class="bill-dt-sl">Order ID - <span class="descp-bll-dt">{{object.order_id}}</span></p>
								<p class="bill-dt-sl">Items - <span class="descp-bll-dt">{{cart_items}}</span></p>
								<p class="bill-dt-sl">Timing - <span class="descp-bll-dt">26 May 2020 , Tuesday, 3.00PM - 5.00PM</span></p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment</h4>
							</div>
							<div class="bill-descp">
								<div class="total-checkout-group p-0 border-top-0">
									<div class="cart-total-dil">
										<h4>Subtotal</h4>
										<span>Ksh : {{object.cart.total }}</span>
									</div>
									<div class="cart-total-dil pt-3">
										<h4>Delivery Charges</h4>
										<span>Ksh : {{object.shipping_total }}</span>
									</div>
								</div>
								<div class="main-total-cart pl-0 pr-0 pb-0 border-bottom-0">
									<h2>Total</h2>
									<span>Ksh : {{object.total }}</span>
								</div>
							</div>
						</div>
						
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment Option</h4>
							</div>
							<div class="bill-descp">
								<p class="bill-dt-sl"><span class="dlr-ttl25 mr-1"><i class="uil uil-check-circle"></i></span>Mpesa</p>
							</div>
						</div>
						<div class="bill-dt-step">
							
							<div class="bill-bottom">
								<div class="thnk-ordr">Thanks You</div>
								
								
									
									
								<a href="{% url 'mpesa:mpesa_waiting' %}" class="print-btn hover-btn" type="submit" >{{delivery_method}}</a>
							
							</div>
					
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Body End -->
	
	<!-- Javascripts -->
	<script src="{ static 'js\jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor\bootstrap\js\bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor\OwlCarousel\owl.carousel.js' %}"></script>
	<script src="{% static 'vendor\semantic\semantic.min.js' %}"></script>
	<script src="{% static 'js\jquery.countdown.min.js' %}"></script>
	<script src="{% static 'js\custom.js' %}"></script>
	<script src="{% static 'js\product.thumbnail.slider.js' %}"></script>
	<script src="{% static 'js\offset_overlay.js' %}"></script>
	<script src="{% static 'js\night-mode.js' %}"></script>
	
	
</body>
</html>

payment/templates/sending_success_payment.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="waiting_container">
        <div class="in_wait">
            <img src="{% static './images/background.png' %}" alt="">
        <h1>Thank You for Payment</h1>
        <p>WE have received the payment,
            
        </p>
        <a style="margin-bottom:20px;" href="{% url 'homepage:homepage' %}" class="btn">Home</a>
        </div>
    </div>
    
</body>
</html>

payment/templates/sucess_booking.html
{% autoescape off %}
Hi {{ user.username }},
Thank you for booking with us
http://{{ domain }}
{% endautoescape %}