account/urls.py
from django.urls import path,include
from .views import (index,signup,activate_account,logout_user,
password_reset,
reset,
change_user)

app_name = "account"

urlpatterns = [
    path('', index,name="sign_in"),
    path('signup/', signup,name="sign_up"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_account, name='activate'),
    path("logout_user/",logout_user,name="logout"),
    path("forgot_password/",password_reset,name="forgot_password"),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        reset, name='reset'),
        path("change_user_password/",change_user,name="change_user"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('',include('homepage.urls',namespace="homepage")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from unicodedata import name
from django.urls import path
from djgeojson.views import GeoJSONLayerView
from .models import Building,Room
from .views import (
    CallGlovoAPiview,
    FilterWithCurrentLocation,
    index,
    map_search_view,
    GetBUildingAPIVIEW,
    GetRoom,
    map_detailed_page,
    FilterRoom,
    room_detailed_page,
    request_booking,
    listing_listview,
    book_request,
    saved_room,
    FilterSavedRoom,
    all_saved_rooms,
    unsaved_room,
    book_room_payment,
    payment_waiting,
    paid_rooms,
    payment_Processing,
    room_detailed_page_paid,
    SendHTML,
    SendContactMail,
    GetRoomAl,
    map_search_view_authenticated,
    PostLocationCoordinates,
    SendContactAdminMail,
    GetCoordinatesAndBounds
)

app_name = "homepage"
urlpatterns = [
    path('', index,name="homepage"),
    path('map_search',map_search_view,name="map_search"),
    path("all_buildinunsaved_roomgs/",GeoJSONLayerView.as_view(model=Building,properties=('agent','building_name','no_of_floors','no_of_Room','location_name','parking_space','security','tv_connection','account_number','owner','payment_deadline','penalties','approved','created')),name="all_buildings"),
    path('get_all_data/',GetBUildingAPIVIEW.as_view(),name="get_all_data"),
    path('room_name/',GetRoom.as_view(),name="get_room"),
    path('map_detailed/<id>/',map_detailed_page,name="map_detailed"),
    path('filter_room/',FilterRoom.as_view(),name="filtered_data"),
    path('room_detailed/<id>/',room_detailed_page,name="room_detailed"),
    path('room_detailed_paid/<id>/',room_detailed_page_paid,name="room_detailed_page_paid"),

    path('booking_request/<room_id>/<agent_id>/<user_id>/',request_booking,name="request_booking"),
    path('listing_listview/',listing_listview,name="listing_listview"),
    path('book_request/<id>/',book_request,name="book_request"),
    path('saved_rentals/<id>/',saved_room,name="saved_rentals"),
    path('filter_saved_rooms/',FilterSavedRoom.as_view(),name="filter_saved_rooms"),
    path('all_saved_rooms/',all_saved_rooms,name="all_saved_rooms"),
    path('unsaved_room/<id>/',unsaved_room,name="unsaved_rentals"),
    path('booking_payment/<id>/',book_room_payment,name="book_room_payment"),
    path("payment_waiting/",payment_waiting,name="payment_waiting"),
    path("paid_rooms/",paid_rooms,name="paid_rooms"),
    path("payment_Processing/",payment_Processing,name="payment_Processing"),
    path("send_mail/kanzi/",SendHTML.as_view()),
    path("send_email_contact_kanzi/",SendContactMail.as_view()),
    path("get_all_rooms/",GetRoomAl.as_view(),name="all_rm"),
    path("map_search_view_authenticated/",map_search_view_authenticated,name="map_search_view_authenticated"),
    path("post_location_coordinates/",PostLocationCoordinates.as_view()),
    path("send_em/",SendContactAdminMail.as_view()),
    path('call_glovo/',CallGlovoAPiview.as_view(),name="call_glovo"),
    path("search_with_lat/",FilterWithCurrentLocation.as_view(),name="search_with_lat_and_lon"),
    path("get_coordinates_and_bounds/",GetCoordinatesAndBounds.as_view(),name="get_coordinates_and_bounds")

  
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.gis.db import models as md
import os
import random

# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "thumbnails/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )



class Agent(md.Model):
    agent_id = models.AutoField(primary_key=True,help_text="agent primary id")
    agent_profile_picture = models.ImageField(upload_to = upload_image_path,blank = True,null =  True,help_text="The agent picture")
    agent_name = models.CharField(max_length=30,help_text="agent name")
    mobile_number = models.CharField(max_length=10,help_text="agent phone number")
    email = models.EmailField(max_length=50,help_text="agent email")
    approved = models.BooleanField(default=False,help_text="approved")
    address = md.PointField(srid=4326,help_text="agent address")

    account_number = models.CharField(max_length=30, help_text="bank account")

    def __str__(self):
        return self.agent_name

    class Meta:
        verbose_name_plural = 'Agents'


class UserManager(BaseUserManager):

    def create_user(self, email, password=None):

        if email is None:
            raise TypeError('Users must have an email address.')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password):

        if password is None:
            raise TypeError('Superusers must have a password.')

        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()

        return user

class User(AbstractUser):

    first_name =  None
    last_name = None
    username = None
    email = models.EmailField(verbose_name='email',max_length=255,unique=True)
    # phone = models.CharField(null=True,max_length=255)
    # account_type = models.CharField(max_length=255,blank=True,null=True)
    # approved =  models.BooleanField(default=False)
    # address_name = models.CharField(max_length=255,blank=True,null=True)
    # latitude =  models.CharField(max_length=100,blank=True,null=True)
    # longitude =  models.CharField(max_length=100,blank=True,null=True)
    objects = UserManager()

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    def get_username(self):
        return self.email

account/forms.py
from django import forms

class SignINForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"email" , "placeholder":"Email", "id":"username",
             "required":""

        }
    ))

    password = forms.CharField(
        widget=forms.PasswordInput(
           attrs={ "type":"password" ,"placeholder":"Password", "id":"password",
            "required":""}
        )
    )

    


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"Username", "id":"username",
             "required":""

        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"First Name", "id":"username",
             "required":""

        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"Last Name", "id":"username",
             "required":""

        }
    ))

    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"phone", "type":"text" , "placeholder":"Phone Number", "id":"phone",
             "required":""

        }
    ))

    type = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"type", "type":"text" , "placeholder":"Type ...", "id":"type",
             "required":""

        }
    ))

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            "name":"emailaddress", "type":"email" , "placeholder":"Username", "id":"email",
             "required":""

        }
    ))

    password = forms.CharField(
        widget=forms.PasswordInput(
           attrs={ "type":"password" ,"placeholder":"Password", "id":"password",
            "required":""}
        )
    )

account/views.py
from django.shortcuts import redirect, render

from homepage.common.SendEmailThread import SendEmailThread
from .forms import SignINForm,SignUpForm
from django.contrib.auth import authenticate,login
# from django.contrib.auth.models import User
from account.models import User
from django.contrib.sites.shortcuts import get_current_site

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.contrib.auth import logout


# Create your views here.

def logout_user(request):
    logout(request)
    return redirect("/")
 
def index(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username,password)
        user = authenticate(request,username = username, password = password )
        print("jjja",user)
        if user is not None:
        
            login(request,user)
            return redirect("homepage:homepage")
        else:
            
            pass
    return render(request,'signin.html')


def signup(request):
   
    if request.method =='POST':
       
            email = request.POST.get('email')
            password = request.POST.get("password")
            user = authenticate(request,username = email, password = password )
            if user is not None:
                print("user exists")
                return redirect("account:sign_in")
            else:
                user = User.objects.create(email = email)
                user.set_password(password)
                user.is_active =  False
                user.save()
                current_site = get_current_site(request)
                email_subject = 'Activate Your Account'
                message = render_to_string('activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                })
                
                
                SendEmailThread(email=email.lower(),message=message,subject=email_subject).start()

                return render(request,'send_email_user.html')
                # userr = authenticate(request,username = email, password = password )
                # if userr is not None:
                #     login(request,userr)
                #     return redirect("homepage:dashboard")

    return render(request,'signup.html')


def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request,user)
        current_site = get_current_site(request)
        email_subject = 'Successfull Registration'
        message = render_to_string('successfull_regestration.html', {
        'user': user,
        'domain': current_site.domain
        })
        to_email = user.email
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()

        return render(request,'your_account_activated.html')
        
    else:
        return render(request,'invalid_link.html')


def password_reset(request):
    msg = ''
    if request.method == "POST":
        email = request.POST.get('email')
        qs = User.objects.filter(email=email)
        site = get_current_site(request)

        if len(qs) > 0:
                user = qs[0]
                user.is_active = False  # User needs to be inactive for the reset password duration
                user.reset_password = True
                user.save()
                

                email_subject = 'Reset Password'
                message = render_to_string('reset_password_email.html', {
                    'user': user,
                    'protocol': 'http',
                    'domain': site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = user.email
                email = EmailMessage(email_subject, message, to=[to_email])
                email.send()

                return HttpResponse('Reset Password Email Sent Successfully')

    
    return render(request,'forgot_password.html')



def reset(request,uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        request.session['user_id'] =  user.id
        return render(request,'password_reset.html')        
    else:
        return HttpResponse('Activation link is invalid!')


def change_user(request):
    user_id =  request.session.get("user_id")
    if request.method == "POST":
        passs =  request.POST.get("password")
        print(passs)
        user_obj =  User.objects.get(id = user_id)
        user_obj.set_password(passs)
        user_obj.save()
        
        del request.session['user_id']
        return redirect("account:sign_in")

            

account/templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}
{% endautoescape %}

account/templates/activation_successful.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    </head>
    <body>
        <h6>Your account has been activate successfully</h6>
        <a class="btn btn-success" href="{% url 'homepage:homepage' %}">Go To Home</a>
    </body>
</html>

account/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>

        {% comment %} {% include 'pre_loader.html' %} {% endcomment %}

        {% include 'header.html' %}

        {% include './forgot_password/section.html' %}
        {% include 'footer.html' %}

    </body>

</html>

account/templates/invalid_link.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>

        {% comment %} {% include 'pre_loader.html' %} {% endcomment %}

        {% include 'header.html' %}

        {% include './invalid_link/invalid_link.html' %}
        {% include 'footer.html' %}

    </body>

</html>

account/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>

        {% comment %} {% include 'pre_loader.html' %} {% endcomment %}

        {% include 'header.html' %}

        {% include './change_user/section.html' %}
        {% include 'footer.html' %}

    </body>

</html>

account/templates/reset_password_email.html
{% autoescape off %}
<h3>
    Hi {{ user.username }},
</h3>

To initiate the password reset process for your account on {{ domain }},
click the link below:
<br><br>
<a href="{{ protocol }}://{{ domain }}{% url 'account:reset' uidb64=uid token=token %}">Reset password</a>
<br><br>
If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

account/templates/send_email_user.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>

        {% comment %} {% include 'pre_loader.html' %} {% endcomment %}

        {% include 'header.html' %}

        {% include './send_email/send_email.html' %}
        {% include 'footer.html' %}

    </body>

</html>

account/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>


      <!-- font awesome cdn link  -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

           <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'login_css/style.css' %}">

</head>
<body>

    <div class="container">
        <form method="POST" action = "{% url 'account:sign_in' %}">
            {% csrf_token %}

            <div class="links">
                <h3 class="title">sign in with</h3>
                <div class="buttons">
                    <!-- <a href="" class="btn">
                        <i class="fab fa-google">
                            google
                        </i>
                    </a> -->

                    <a href="{% url 'social:begin' 'facebook' %}" class="btn">
                        <i class="fab fa-facebook-f">
                           Facebook
                        </i>
                    </a>
                </div>

            </div>

            <div class="input-box">
                <h3 class="title">or sign in with</h3>
                <div class="input">
                    <span class="far fa-envelope"></span>
                    <input type="email" name="username" placeholder="email" id="">

                </div>

                <div class="input">
                    <span class="fas fa-lock"></span>
                    <input type="password" name="password" placeholder="password" id="">

                </div>
              
                <input type="submit" value="sign in" class="sign-in-btn">
                <a href="{% url 'account:sign_up' %}" style="    padding: 10px 14px;
                margin-top: 10px;
                font-size: 17px;
                color: #fff;
                border-radius: 5px;
                background: black;
                cursor: pointer;
                -webkit-transition: .2s linear;
                transition: .2s linear;">Sign Up</a>
            </div>
        </form>
    </div>
    
</body>
</html>

account/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>


      <!-- font awesome cdn link  -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

           <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'login_css/style.css' %}">

</head>
<body>

    <div class="container">
    <form method="POST" action = "{% url 'account:sign_up' %}">
            {% csrf_token %}

            <div class="links">
                <h3 class="title">sign up with</h3>
                <div class="buttons">
                    <!-- <a href="" class="btn">
                        <i class="fab fa-google">
                            google
                        </i>
                    </a> -->

                    <a href="{% url 'social:begin' 'facebook' %}" class="btn">
                        <i class="fab fa-facebook-f">
                            Facebook
                        </i>
                    </a>
                </div>

            </div>

            <div class="input-box">
                <h3 class="title">or sign up with</h3>
                <div class="input">
                    <span class="far fa-envelope"></span>
                    <input type="email" name="email" placeholder="email" id="">

                </div>

                <div class="input">
                    <span class="fas fa-lock"></span>
                    <input type="password" name="password" placeholder="password" id="">

                </div>
              
                <input type="submit" value="sign up" class="sign-in-btn">
                <a href="{% url 'account:sign_in' %}" style="    padding: 10px 14px;
                margin-top: 10px;
                font-size: 17px;
                color: #fff;
                border-radius: 5px;
                background: black;
                cursor: pointer;
                -webkit-transition: .2s linear;
                transition: .2s linear;">Sign In</a>
            </div>
        </form>
    </div>
    
</body>
</html>

account/templates/successfull_regestration.html
{% autoescape off %}
Hi {{ user.username }},
Thank you for registering with us, follow this link to go to homepage
http://{{ domain }}
{% endautoescape %}

account/templates/your_account_activated.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    <body>

        {% comment %} {% include 'pre_loader.html' %} {% endcomment %}

        {% include 'header.html' %}

        {% include './activated_account/success.html' %}
        {% include 'footer.html' %}

    </body>

</html>