account/urls.py
from django.urls import path,include
from .views import (index,signup,activate_account,logout_user,
password_reset,
reset,
change_user)

app_name = "account"

urlpatterns = [
    path('', index,name="sign_in"),
    path('signup/', signup,name="sign_up"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_account, name='activate'),
    path("logout_user/",logout_user,name="logout"),
    path("forgot_password/",password_reset,name="forgot_password"),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        reset, name='reset'),
        path("change_user_password/",change_user,name="change_user"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('',include('homepage.urls',namespace="homepage")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from unicodedata import name
from django.urls import path
from djgeojson.views import GeoJSONLayerView
from .models import Building,Room
from .views import (
    CallGlovoAPiview,
    FilterWithCurrentLocation,
    index,
    map_search_view,
    GetBUildingAPIVIEW,
    GetRoom,
    map_detailed_page,
    FilterRoom,
    room_detailed_page,
    request_booking,
    listing_listview,
    book_request,
    saved_room,
    FilterSavedRoom,
    all_saved_rooms,
    unsaved_room,
    book_room_payment,
    payment_waiting,
    paid_rooms,
    payment_Processing,
    room_detailed_page_paid,
    SendHTML,
    SendContactMail,
    GetRoomAl,
    map_search_view_authenticated,
    PostLocationCoordinates,
    SendContactAdminMail,
    GetCoordinatesAndBounds
)

app_name = "homepage"
urlpatterns = [
    path('', index,name="homepage"),
    path('map_search',map_search_view,name="map_search"),
    path("all_buildinunsaved_roomgs/",GeoJSONLayerView.as_view(model=Building,properties=('agent','building_name','no_of_floors','no_of_Room','location_name','parking_space','security','tv_connection','account_number','owner','payment_deadline','penalties','approved','created')),name="all_buildings"),
    path('get_all_data/',GetBUildingAPIVIEW.as_view(),name="get_all_data"),
    path('room_name/',GetRoom.as_view(),name="get_room"),
    path('map_detailed/<id>/',map_detailed_page,name="map_detailed"),
    path('filter_room/',FilterRoom.as_view(),name="filtered_data"),
    path('room_detailed/<id>/',room_detailed_page,name="room_detailed"),
    path('room_detailed_paid/<id>/',room_detailed_page_paid,name="room_detailed_page_paid"),

    path('booking_request/<room_id>/<agent_id>/<user_id>/',request_booking,name="request_booking"),
    path('listing_listview/',listing_listview,name="listing_listview"),
    path('book_request/<id>/',book_request,name="book_request"),
    path('saved_rentals/<id>/',saved_room,name="saved_rentals"),
    path('filter_saved_rooms/',FilterSavedRoom.as_view(),name="filter_saved_rooms"),
    path('all_saved_rooms/',all_saved_rooms,name="all_saved_rooms"),
    path('unsaved_room/<id>/',unsaved_room,name="unsaved_rentals"),
    path('booking_payment/<id>/',book_room_payment,name="book_room_payment"),
    path("payment_waiting/",payment_waiting,name="payment_waiting"),
    path("paid_rooms/",paid_rooms,name="paid_rooms"),
    path("payment_Processing/",payment_Processing,name="payment_Processing"),
    path("send_mail/kanzi/",SendHTML.as_view()),
    path("send_email_contact_kanzi/",SendContactMail.as_view()),
    path("get_all_rooms/",GetRoomAl.as_view(),name="all_rm"),
    path("map_search_view_authenticated/",map_search_view_authenticated,name="map_search_view_authenticated"),
    path("post_location_coordinates/",PostLocationCoordinates.as_view()),
    path("send_em/",SendContactAdminMail.as_view()),
    path('call_glovo/',CallGlovoAPiview.as_view(),name="call_glovo"),
    path("search_with_lat/",FilterWithCurrentLocation.as_view(),name="search_with_lat_and_lon"),
    path("get_coordinates_and_bounds/",GetCoordinatesAndBounds.as_view(),name="get_coordinates_and_bounds")

  
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>

  
      <!-- font awesome cdn link  -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
     
          <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra_head %} 

    {% endblock extra_head %}


</head>
<body>


    <!-- header section starts  -->

<header>

    <a href="#" class="logo">
        <img src="{% static '/images/background.png' %}" alt="">
    </a>

    {% block header_form %}



{% endblock header_form %}

    <nav class="navbar">

        <ul>

            <li><a href="/">home</a></li>
            <li><a href="#">services</a></li>
            <li><a href="#">featured</a></li>
            
            <li><a href="{% url 'homepage:map_search' %}">all houses</a></li>
            <li><a href="{% url 'homepage:listing_listview' %}">For rent</a></li>
            <li><a href="#contact">contact</a></li>
            
        </ul>
        
        
        
        
        
        
    </nav>

    <div class="icons">
        <div id="menu-bars" class="fas fa-bars"></div>
        <ul>
            
            <li><a href="#" class="fas fa-user"> </a>
                <ol class="droptwo">
                    {% if user.is_authenticated %}
                    <li>Profile</li>
                    <li> <a href="{% url 'homepage:all_saved_rooms' %}">Saved rentals</a></li>
                    <li><hr></li>
                    
                    <li><a href="{% url 'homepage:paid_rooms' %}">Paid Rooms</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'account:sign_in' %}">Login</a></li>

                    {% endif %}
                    
                    
                    <li><br></li>
    
                </ol></li>
            
        </ul>
        
        
    </div>

</header>

<!-- header section ends -->

{% block content %}{% endblock content %}


<!-- javascript part  -->


<script src="https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="{% static '/js/custome.js' %}"></script>


{% block extra_js %}{% endblock extra_js %}

</body>
</html>