config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('',include('homepage.urls',namespace="homepage")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from unicodedata import name
from django.urls import path
from djgeojson.views import GeoJSONLayerView
from .models import Building,Room
from .views import (
    CallGlovoAPiview,
    FilterWithCurrentLocation,
    index,
    map_search_view,
    GetBUildingAPIVIEW,
    GetRoom,
    map_detailed_page,
    FilterRoom,
    room_detailed_page,
    request_booking,
    listing_listview,
    book_request,
    saved_room,
    FilterSavedRoom,
    all_saved_rooms,
    unsaved_room,
    book_room_payment,
    payment_waiting,
    paid_rooms,
    payment_Processing,
    room_detailed_page_paid,
    SendHTML,
    SendContactMail,
    GetRoomAl,
    map_search_view_authenticated,
    PostLocationCoordinates,
    SendContactAdminMail,
    GetCoordinatesAndBounds
)

app_name = "homepage"
urlpatterns = [
    path('', index,name="homepage"),
    path('map_search',map_search_view,name="map_search"),
    path("all_buildinunsaved_roomgs/",GeoJSONLayerView.as_view(model=Building,properties=('agent','building_name','no_of_floors','no_of_Room','location_name','parking_space','security','tv_connection','account_number','owner','payment_deadline','penalties','approved','created')),name="all_buildings"),
    path('get_all_data/',GetBUildingAPIVIEW.as_view(),name="get_all_data"),
    path('room_name/',GetRoom.as_view(),name="get_room"),
    path('map_detailed/<id>/',map_detailed_page,name="map_detailed"),
    path('filter_room/',FilterRoom.as_view(),name="filtered_data"),
    path('room_detailed/<id>/',room_detailed_page,name="room_detailed"),
    path('room_detailed_paid/<id>/',room_detailed_page_paid,name="room_detailed_page_paid"),

    path('booking_request/<room_id>/<agent_id>/<user_id>/',request_booking,name="request_booking"),
    path('listing_listview/',listing_listview,name="listing_listview"),
    path('book_request/<id>/',book_request,name="book_request"),
    path('saved_rentals/<id>/',saved_room,name="saved_rentals"),
    path('filter_saved_rooms/',FilterSavedRoom.as_view(),name="filter_saved_rooms"),
    path('all_saved_rooms/',all_saved_rooms,name="all_saved_rooms"),
    path('unsaved_room/<id>/',unsaved_room,name="unsaved_rentals"),
    path('booking_payment/<id>/',book_room_payment,name="book_room_payment"),
    path("payment_waiting/",payment_waiting,name="payment_waiting"),
    path("paid_rooms/",paid_rooms,name="paid_rooms"),
    path("payment_Processing/",payment_Processing,name="payment_Processing"),
    path("send_mail/kanzi/",SendHTML.as_view()),
    path("send_email_contact_kanzi/",SendContactMail.as_view()),
    path("get_all_rooms/",GetRoomAl.as_view(),name="all_rm"),
    path("map_search_view_authenticated/",map_search_view_authenticated,name="map_search_view_authenticated"),
    path("post_location_coordinates/",PostLocationCoordinates.as_view()),
    path("send_em/",SendContactAdminMail.as_view()),
    path('call_glovo/',CallGlovoAPiview.as_view(),name="call_glovo"),
    path("search_with_lat/",FilterWithCurrentLocation.as_view(),name="search_with_lat_and_lon"),
    path("get_coordinates_and_bounds/",GetCoordinatesAndBounds.as_view(),name="get_coordinates_and_bounds")

  
]

payment/urls.py
from os import name
from django.urls import path

from .views import (


    LipaNaMpesa,
    confirmation_url,
    customer_to_business,
    LipaNaMpesaC2B

)

app_name = "payment"
urlpatterns = [
    path('lipa_na_mpesa/',LipaNaMpesa.as_view(),name="lipa_online_mpesa"),
    path("confirmation_url/",confirmation_url,name="sending_to_mpesa"),
    path("customer_to_business/",customer_to_business,name="customer_to_business"),
    path("pay_c2b/",LipaNaMpesaC2B.as_view(),name="c2b_p")
   
  
 

]

homepage/views.py
import json
# from django.contrib.gis.geos import Polygon
from fuzzywuzzy import fuzz

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from account.models import  User
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Min,Max

from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from homepage.common.CallGlovo import CallGlovo
from homepage.common.CallLeafet import GetLeafletDate
from homepage.common.SendEmailThread import SendEmailThread

from homepage.common.sendsms import sendSms
from homepage.sendEmailT import SendEmailKanzi

from .models import BookingRequest, Building, BuildingMorePic, Coordinated, MapLocations, Room, RoomMorePic, SavedRooms, SlidingImages,BookTour
from .serializers import BuildingSerializer, CoordinatedSerializer, RoomSerializer, SavedRoomSerializers

from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from shapely.geometry import Point, Polygon 


# Create your views here.
def index(request):

    if request.user.is_authenticated:
            all_room =  Room.objects.filter(approved = True,paid = False)
            user_obj =  User.objects.get(id = request.user.id)
            all_sliding =  SlidingImages.objects.first()
            all_room_pic =  RoomMorePic.objects.all()
            all_room_pic_count =  RoomMorePic.objects.count()
            saved_rentals =  SavedRooms.objects.filter(user =  user_obj,liked=True)
            print(saved_rentals)
            empty_list = []
            if saved_rentals:
               
                for j in  all_room:
                    try:
                        sv = SavedRooms.objects.get(user =  user_obj,liked=True,room__id = j.id)
                       
                        dicti = {}
                        dicti['room'] = j
                        dicti['saved'] = True
                        empty_list.append(dicti)
                    except SavedRooms.DoesNotExist:
                        dicti = {}
                        dicti['room'] = j
                        dicti['saved'] = False
                        empty_list.append(dicti)



                    


                
                            
                       

            else:
                for i in  all_room:
                        dicti = {}
                        dicti['room'] = i
                        dicti['saved'] = False
                        empty_list.append(dicti)

            print(empty_list)


                    
            
            # get current ip
            
            context = {
                'rooms' :  empty_list[:6],
                'sliding' :  all_sliding,
                'all_room_pic_count' : all_room_pic_count,
                'all_room_pic' : all_room_pic,
                'saved_rentals':saved_rentals
                
            }
            return render(request,'index.html',context)


    all_room =  Room.objects.filter(approved = True,paid = False)
    all_sliding =  SlidingImages.objects.first()
    all_room_pic =  RoomMorePic.objects.all()
    all_room_pic_count =  RoomMorePic.objects.count()
    # get current ip
    empty_list= []
    for i in  all_room:
                dicti = {}
                dicti['room'] = i
                dicti['saved'] = False
                empty_list.append(dicti)

    print(empty_list)


    
    context = {
        'rooms' :  empty_list[:6],
        'sliding' :  all_sliding,
        'all_room_pic_count' : all_room_pic_count,
        'all_room_pic' : all_room_pic,
        'saved_rentals':None
        
    }
    return render(request,'index.html',context)


def map_search_view(request):
    if request.is_ajax and request.method == "POST":
        location =  request.POST.get("location_search")
        
        
        app =  GetLeafletDate(location)
        
        loc= app.get_data()[0]
        osm_id = loc['osm_id']

        js_p = app.getLeafletPolygon()
     
        empty_list_2 = []

        for m in js_p:
             if len(m['geojson']['coordinates']) < 2:
                 empty_list_2.append(m)
        print("jjs",empty_list_2)
    
        if len(empty_list_2) >0:
            geojson = empty_list_2[0]['geojson']['coordinates']
            boundingbox = empty_list_2[0]['boundingbox']
            print("jsp",geojson)
            print("boundingbox",boundingbox)
            
      

        else:
            geojson = []
            boundingbox = []
            print("jsp",geojson)


    
        # print("pp",loc['osm_id'])
        # print("nodes",nodes)
    

        
        rms =  Room.objects.filter(approved = True,paid = False)
        empty_list = []
        for i in rms:
        
            empty_list.append(i)



        all_rooms =  Room.objects.filter(approved = True,paid = False)
        split_loc = location.split(",")[0]
        if len(boundingbox) > 0:
            context= {
                'boundingbox':boundingbox,
                'main_lat': float(loc['lat']),
                'main_lng': float(loc['lon']),
                'coordinates' : geojson,
                'criteria_mk' : location,
                "xmin":float(boundingbox[0]),
                "xmax":float(boundingbox[1]),
                "ymin" : float(boundingbox[2]),
                "ymax" : float(boundingbox[3]),
                'formatted' : f"Search for : {split_loc}",
                'all_rooms'  : all_rooms
            }
            return render(request,'map_edited.html',context)
        
        else:
            context= {
                
            
                'boundingbox':boundingbox,
                'main_lat': float(loc['lat']),
                'main_lng': float(loc['lon']),
                'coordinates' : geojson,
                'criteria_mk' : location,
                "xmin":float(0),
                "xmax":float(0),
                "ymin" : float(0),
                "ymax" : float(0),
                'formatted' : f"Search for : {split_loc}",
                'all_rooms'  : all_rooms
            }

            return render(request,'map_edited.html',context)
        
    app =  GetLeafletDate("Kenya")
        
    loc= app.get_data()[0]
    osm_id = loc['osm_id']

    js_p = app.getLeafletPolygon()
    
    empty_list_2 = []

    for m in js_p:
            if len(m['geojson']['coordinates']) < 2:
                empty_list_2.append(m)
    print("jjs",empty_list_2)

    if len(empty_list_2) >0:
        geojson = empty_list_2[0]['geojson']['coordinates']
        boundingbox = empty_list_2[0]['boundingbox']
        print("jsp",geojson)
        print("boundingbox",boundingbox)
        
    

    else:
        geojson = []
        boundingbox = []
        print("jsp",geojson)



    # print("pp",loc['osm_id'])
    # print("nodes",nodes)


    
    rms =  Room.objects.filter(approved = True,paid = False)
    empty_list = []
    for i in rms:
    
        empty_list.append(i)



    all_rooms =  Room.objects.filter(approved = True,paid = False)
    if len(boundingbox) > 0:
        context= {
            'boundingbox':boundingbox,
            'main_lat': float(loc['lat']),
            'main_lng': float(loc['lon']),
            'coordinates' : geojson,
            "xmin":float(boundingbox[0]),
            "xmax":float(boundingbox[1]),
            "ymin" : float(boundingbox[2]),
            "ymax" : float(boundingbox[3]),
            
            'all_rooms'  : all_rooms
        }
        return render(request,'map_edited.html',context)
    
    else:
        context= {
            
        
            'boundingbox':boundingbox,
            'main_lat': float(loc['lat']),
            'main_lng': float(loc['lon']),
            'coordinates' : geojson,
            "xmin":float(0),
            "xmax":float(0),
            "ymin" : float(0),
            "ymax" : float(0),
         
            'all_rooms'  : all_rooms
        }

        return render(request,'map_edited.html',context)
    

class GetBUildingAPIVIEW(APIView):
    def get(self, request):
        buidlings = Building.objects.all()
        print(buidlings)
        # the many param informs the serializer that it will be serializing more than a single article.
        serializer = BuildingSerializer(buidlings,many = True)
        return Response(serializer.data)


    def post(self,request):
        id =  request.data['id']
        print("the id",id)
        buidlings = Building.objects.get(id = int(id))
        print("building d",buidlings)
        # the many param informs the serializer that it will be serializing more than a single article.
        serializer = BuildingSerializer(buidlings)
        return Response(serializer.data)



class GetRoomAl(APIView):
    def get(self,request):
        criteria = request.query_params
        print(criteria)
        all_roomms = Room.objects.filter(approved = True,paid = False)
        room_serializer =  RoomSerializer(all_roomms,many = True)
        return Response(room_serializer.data)


    def post(self,request):
      
        criteria_location =  request.data['criteria_location']
        xmin =  request.data['xminm']
        xmax =  request.data['xmaxm']
        ymin =  request.data['yminm']
        ymax =  request.data['ymaxm']

        bbbox = (float(xmin),float(ymin),float(ymax),float(xmax))

        pp =  Polygon.from_bounds(xmin=float(xmin),ymin=float(ymin),xmax=float(xmax),ymax=float(ymax))
        print("oo",pp)
        print("xmin",xmin)
        print("lloo",json.loads(json.dumps((criteria_location))))

        building_filter  = Building.objects.all()
        print("buiding filter",building_filter)
   

        rms =  Room.objects.filter(approved = True,paid = False)
        empty_list = []
        for i in rms:
            for j in building_filter:

homepage/templates/app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kanzi Html</title>
</head>
<body style="margin: 0; padding: 0;border: 1px solid black; margin-top: 20px;margin-right: 5rem;margin-left: 5rem;margin-bottom: 5rem;box-sizing: border-box;" >

    <style>

        .logo_holder{
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            margin-top: 30px;
        }

        .logo_holder h1{
            font-size: 20px;
        }

        .content{
       
            display: flex;
         
         
            justify-content: space-evenly;
       
            width: 100%;
            height: 100vh;
            margin: 20px;
            
        }

        .content .additional_information{
            margin-right: 3rem;

        }

        h2{
            font-size: 18px;

        }

        .htc__footer__top{
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .copyright__inner{
            display: flex;
            align-items: center;
            justify-content: space-between;
            color: white;
        }

        .footer__menu{
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: space-between;
            list-style: none;
            margin-left: 1rem;
            margin-right: 1rem;
        }

      

      

    
        

    </style>

    <div class="logo_holder">
        <img src="{% static './4.png' %}" alt="" srcset="">

        <h1>Admission Form</h1>

        <h2 style="text-align: center;">Times Tower Building <br> Haile Selassie Avenue <br> P. O. Box 48240 - 00100 <br> Tel +254 20 281 0000 <br> Email: callcentre@kra.go.ke</h2>
    
    </div>

    <div class="content">
        <div class="child_information">
            <h2>Child's Information</h2>

            <table style="height: 40vh;">
                <tr>
                    <td>First Name : </td>
                    <td style="color: #666;">{{fname}}</td>
                </tr>

                <tr>
                    <td>Last Name : </td>
                    <td style="color: #666;">{{lname}}</td>
                </tr>

                <tr>
                    <td>Surname Name : </td>
                    <td style="color: #666;">{{sname}}</td>
                </tr>

                <tr>
                    <td>Date of birth : </td>
                    <td style="color: #666;">{{dob}}</td>
                </tr>

                <tr>
                    <td>Gender : </td>
                    <td style="color: #666;">{{gender}}</td>
                </tr>


                <tr>
                    <td>Current School : </td>
                    <td style="color: #666;">{{current_school}}</td>
                </tr>
            </table>
        </div>

        <div class="additional_information">
            <h2>Additional Information</h2>

            <table style="height: 40vh;">
                <tr>
                    <td >Grade interested in :</td>
                    <td style="color: #666;">{{gade_intrested}}</td>
                </tr>

                <tr>
                    <td>Contact information : </td>
                    <td style="color: #666;">{{contact_info}}</td>
                </tr>

                <tr>
                    <td>Person inquiring : </td>
                    <td style="color: #666;">{{person_inquiring}}</td>
                </tr>

                <tr>
                    <td>Mobile Number : </td>
                    <td style="color: #666;">{{mobile_number}}</td>
                </tr>

                <tr>
                    <td>Email Address : </td>
                    <td style="color: #666;">{{email_address}}</td>
                </tr>

                <tr>
                    <td>Physical Address Address : </td>
                    <td style="color: #666;">{{physical_address}}</td>
                </tr>

                <tr>
                    <td>How did you hear about us : </td>
                    <td style="color: #666;">{{knwo_abt_kanzi}}</td>
                </tr>
            </table>
        </div>

    </div>

  
  
    <footer style="background-color:#05204a;" class="htc__footer__area bg__theme">
        <div class="container">
            <!-- Start Footer Top Area -->
            
            <!-- End Footer Top Area -->

            <!-- Start Contact Area -->
     
    <!-- End Contact Area -->

            
            <!-- Start Foooter Menu Area -->
            <div style="height: 150px;" class="htc__footer__top">
                <div class="row">   
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <div class="">
                            <div class="">
                                <a href="index.html">
                                    <img src="{% static './4.png' %}" alt="footer logo">
                                </a>
                            </div>
                         
                        </div>
                    </div>
                </div>
            </div>
        
            <!-- End Foooter Menu Area -->
            <!-- Start Copyright Area -->
            <div class="htc__copyright__area">
                <div class="row">
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <div class="copyright__inner">
                           
                            <ul class="footer__menu">
                                <li>Phone : 0714608899</li>
                                <li>Whatsapp : 0780 877898</li>
                                <li>Email : info@kanzischool.sc.ke</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Copyright Area -->
        </div>
    </footer>
    
</body>
</html>

homepage/templates/awaiting_c2b.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>
    <link rel="stylesheet" href="{% static  'css/style.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
</head>

<body class="payment_body">
    <div class="wrapper">
        <h2>Customer To Business</h2>
        <form id="payment_c2b" method="post">
            {% csrf_token %}
          
            <div class="input_group">
                <div class="input_box">
                    <input style="text-transform: lowercase;" type="text" name="full_name" placeholder="Enter Full Name" required class="name">
                    <i class="fa fa-user icon"></i>
                </div>
            </div>
            <div class="input_group">
                <div class="input_box">
                    <input style="text-transform: lowercase;" type="email" name="email" placeholder="Enter Email" required class="name">
                    <i class="fa fa-envelope icon"></i>
                </div>
            </div>
          
            <div class="input_group">
                <div class="input_box">
                    <input style="text-transform: lowercase;" type="number" name="payment_amount" placeholder="Payment Amount" required class="name">
                    <i class="fa fa-coins icon"></i>
                </div>
            </div>
            <div class="input_group">
                <div class="input_box">
                    <input type="tel" name="phone_number" placeholder="Paying Phone Number" required class="name">
                    <i class="fa fa-phone icon" aria-hidden="true"></i>
                </div>
            </div>
           
            <!--Account Information End-->
            

            <input type="hidden" name="room_number" value = "{{specific_room.id}}">
         
            <!--Payment Details End-->
            <div id="animation_holder" class="animation_holder">
                
            </div>
            <div class="input_group">
                <input type="hidden" name="payment_option" value = "mpesa">
                <div id="submit_btn" class="input_box">
                    <button  type="submit">PAY NOW</button>
                </div>
            </div>

        </form>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static './js/payment_option.js' %}"></script>

   <script>
       function pay_with_mpesa_c2b(dicti){
           console.log(dicti)

               
           var id_user = {{request.user.id}}

           $.ajax({
                type: 'POST',
                url: "{% url 'payment:c2b_p' %}",
                data: {'user_id':id_user,'payment':`${JSON.stringify(dicti)}`,'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (response) {
                    console.log(response) ;
                    window.location.replace("{% url 'homepage:payment_Processing' %}"); 
                  
                },
                error: function (response) {
                    // alert the error if any error occured
                    console.log(response["responseJSON"]["error"]);
                    const animation_holder  =  $('#animation_holder')
                    animation_holder.empty()

                    const btn = $('#submit_btn')
                    btn.empty();

                    const v = `<button  type="submit">PAY NOW</button>`;
                    btn.append(v);
                }
            })
        
       }
   </script>
</body>

</html>
        

homepage/templates/booking_request.html
<h1>Booking request</h1>

homepage/templates/payment_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentobay</title>
    <link rel="stylesheet" href="{% static  'css/style.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
</head>

<body class="payment_body">
    <div class="wrapper">
        <h2>Booking Form</h2>
        <form id="payment_form_form" method="post">
            <!--Account Information Start-->
            <h4>Account</h4>
            <div class="input_group">
                <div class="input_box">
                    <input type="text" name="full_name" placeholder="Full Name" required class="name">
                    <i class="fa fa-user icon"></i>
                </div>
                <div class="input_box">
                    <input type="number" name="id_number" placeholder="Id Number" required class="name">
                    <i class="fa fa-user icon"></i>
                </div>
            </div>
            <div class="input_group">
                <div class="input_box">
                    <input style="text-transform: lowercase;" type="email" name="emai_address" placeholder="Email Address" required class="name">
                    <i class="fa fa-envelope icon"></i>
                </div>
            </div>
            <div class="input_group">
                <div class="input_box">
                    <input type="tel" name="contact_number" placeholder="Contact Phone Number" required class="name">
                    <i class="fa fa-phone icon" aria-hidden="true"></i>
                </div>
            </div>
           
            <!--Account Information End-->
            

            <!--Payment Details Start-->
            <div class="input_group">
                <div  class="input_box">
                    <h4>Mpesa Payment</h4>
                    <!-- <input onclick="check_which()" type="radio" name="pay" class="radio" id="bc1" checked> -->
                    <!-- <label for="bc1"><span>Credit Card</span></label> -->
                    <!-- <input width="100%" onclick="check_which()" type="radio" name="pay" class="radio" id="bc2">
                    <label for="bc2"><span >
                            Mpesa</span></label> -->
                </div>
            </div>

            
            <input type="hidden" name="room_number" value = "{{specific_room.id}}">
            <div id="payment_collection">
                <!-- <div class="input_group">
                    <div class="input_box">
                        <input type="tel" name="card_number" class="name" placeholder="Card Number 1111-2222-3333-4444" required>
                        <i class="fa fa-credit-card icon"></i>
                    </div>
                </div>
                <div class="input_group">
                    <div class="input_box">
                        <input type="tel" name="card_cvc" class="name" placeholder="Card CVC 632" required>
                        <i class="fa fa-user icon"></i>
                    </div>
                </div>
                <div class="input_group">
                    <div class="input_box">
                        <div class="input_box">
                            <input type="number" name="expire_month" placeholder="Exp Month" required class="name">
                            <i class="fa fa-calendar icon" aria-hidden="true"></i>
                        </div>
                    </div>
                    <div class="input_box">
                        <input type="number" name="expire_year" placeholder="Exp Year" required class="name">
                        <i class="fa fa-calendar-o icon" aria-hidden="true"></i>
                    </div>
                </div> -->
                
                <div class="input_group">
                    <div class="input_box">
                    <input type="hidden" name="payment_option" value = "mpesa">
                        <input type="tel" name="mpesa_payment" class="name" placeholder="Mpesa Phone Number" required>
                        <i class="fa fa-phone icon"></i>
                    </div>
                </div>
            </div>
            <!--Payment Details End-->
            <div id="animation_holder" class="animation_holder">
                
            </div>
            <div class="input_group">
                <div id="submit_btn" class="input_box">
                    <button  type="submit">PAY NOW</button>
                </div>
            </div>

        </form>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static './js/payment_option.js' %}"></script>

   <script>
       function pay_with_mpesa(dicti){
           console.log(dicti)

               
           var id_user = {{request.user.id}}

           $.ajax({
                type: 'POST',
                url: "{% url 'payment:lipa_online_mpesa' %}",
                data: {'user_id':id_user,'payment':`${JSON.stringify(dicti)}`,'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (response) {
                    console.log(response) ;
                    window.location.replace("{% url 'homepage:payment_waiting' %}"); 
                  
                },
                error: function (response) {
                    // alert the error if any error occured
                    console.log(response["responseJSON"]["error"]);
                    const animation_holder  =  $('#animation_holder')
                    animation_holder.empty()

                    const btn = $('#submit_btn')
                    btn.empty();

                    const v = `<button  type="submit">PAY NOW</button>`;
                    btn.append(v);
                }
            })
        
       }
   </script>
</body>

</html>
        